### ISSUE TITLE
API functions tracker

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/observatory-extension#15]
## Pre-rollout functions

- [x] OBS_GetDemographicSnapshot( Point Geometry );
- [x] OBS_GetSegmentationSnapshot( Point Geometry );

## Augmentation Usage Scenarios

- [x] OBS_GetPopulation(Point Geometry)
- [x] OBS_GetPopulation(Polygon Geometry);
- [x] OBS_GetMeasure(Point Geometry, Measure ID);
- [x] OBS_GetMeasure(Polygon Geometry, Measure ID);
- [x] OBS_GetCategory(Point Geometry, Simple name);
- [x] OBS_GetCategory(Polygon Geometry, Simple name);
- [x] OBS_GetUSCensusMeasure(Point Geometry, Simple name);
- [x] OBS_GetUSCensusMeasure(Polygon Geometry, Simple name);
- [x] OBS_GetUSCensusCategory(Point Geometry, Simple name);
- [x] OBS_GetUSCensusCategory(Polygon Geometry, Simple name);

## Boundary Usage Scenarios 

- [x] OBS_GetGeometry(Point Geometry, Boundary Layer);
- [x] OBS_GetGeometryId(Point Geometry, Boundary Layer ID );

## Discovery Usage Scenarios

- [x] OBS_Search(Search Term, Relevant Boundary);
- [x] OBS_GetAvailableBoundaries(Relevant Geometry);
- [x] OBS_GetGeometryId( Boundary Layer ID, Boundary ID );

cc @stuartlynn @talos @ohasselblad these should match the Guide document. They should also be pushed ASAP as a new branch (not the abandoned branch). Does that all look clear with final naming? I've left out the tag/theme search for now because it wasn't clear to me the methods.

**Comment by talos** [comment]
All functions are in https://github.com/CartoDB/observatory-extension/pull/30 .
