### ISSUE TITLE
Meta-issue: issues spotted in develop branch

### ISSUE THREAD

**Issue by iriberri** [CartoDB/observatory-extension#52]
* [x] Some of the functions are using parameters of type `Geometry`, while others are using `geometry(Geometry, 4326)`
  We're assuming this has not been done on purpose, so we should try to make the types homogeneous. We suggest using `geometry(Geometry, 4326)` for all those `Geometry` 

* [x] We're also seeing that even though `geometry(Geometry, 4326)` is used, the expected geometry type is a point. We suggest using `geometry(Point, 4326)` in those cases.

* [x] Some function signatures do not include the schema
  Example: https://github.com/CartoDB/observatory-extension/blob/release-v1-alpha/src/pg/sql/42_observatory_exploration.sql#L84
  
* [x] Some parameters (as boundary_id) appear in the code but are not documented
  See code here: https://github.com/CartoDB/observatory-extension/blob/develop/src/pg/sql/41_observatory_augmentation.sql#L392
  See doc here: https://github.com/CartoDB/observatory-extension/blob/release-v1-alpha/doc/methods.md#obs_getuscensusmeasurepoint_geometry-measure_name

* [x] Return type typo in https://github.com/CartoDB/observatory-extension/blob/release-v1-alpha/doc/methods.md#returns-2, which should be text

* [x] 6 of the functions are returning tables: https://github.com/CartoDB/dataservices-api/issues/175

* [x] ERROR:  parameter name "time_span" used more than once; CONTEXT:  compilation of PL/pgSQL function "obs_getavailableboundaries" near line 1

* [x] DB dump needed for the v1 release #59 (not actually a dev issue but here for keeping track of the tasks face to the release)

* [x] For the next DB dump: have it in the agreed S3 bucket, as otherwise the deploy scripts need to be adapted aside from the slowness of downloading (and I guess uploading) from other place. cc/ @talos 

* [x] ~~Return type for obs_getdemographicsnapshot and obs_getsegmentsnapshot has changed from [JSON](https://github.com/CartoDB/observatory-extension/blob/qlik-alfa-plproxy/src/pg/sql/41_observatory_augmentation.sql#L26) to [SETOF](https://github.com/CartoDB/observatory-extension/blob/release-v1-alpha/src/pg/sql/41_observatory_augmentation.sql#L28) json which breaks backward compatibility~~ - update: just ignore them FTM.

* [ ] We need the SQL files to install the extension: total installation, upgrade and downgrade

**Comment by ohasselblad** [comment]
For **1 and 2.** Should we do the same for casting, like `NULL::geometry(Point, 4326`?

**Comment by ethervoid** [comment]
Another more issue added @ohasselblad , some changes made breaks backward compatibility with qlik

**Comment by ohasselblad** [comment]
@ethervoid, adding @stuartlynn here for that issue

**Comment by rafatower** [comment]
@stuardlet that json issue be for the moment, we'll look into it. Maybe it's just a matter of merging `qlik-alfa-plproxy`

**Comment by rafatower** [comment]
@ohasselblad and @stuartlynn actually I checked and the changes for `qlik-alfa-plproxy` were already merged back to `develop` and that basically means that indeed you broke the compatibility and need to look into it to fix what's already in production.

**Comment by stuartlynn** [comment]
Hey @rafatower. The Qlik account probably shouldn't be updated to the new functions, it should remain on the old branch we developed for Qlik. We collectively, I think, decided to move to json responses for the functions that where in there not table returning ones. That means it was always going to break backwards compatibility with the Qlik deploy.

**Comment by ethervoid** [comment]
The problem @stuartlynn is that this functions break compatibility for the server side so we aren't able to have 1 user with a different version of the server part. That could be work in the client side.

In summary, we aren't able to have some branch/version for some clients in the server side part that's why we need to avoid this kind of situations.

**Comment by rafatower** [comment]
Just spoke with Andrew: just disregard the `obs_getdemographicsnapshot` and `obs_getsegmentsnapshot` function signature change. It's totally ok to break compat with them.

**Comment by stuartlynn** [comment]
Great! Thats good news. Thanks @rafatower @ethervoid
